require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/emails", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Email. As you add validations to Email, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Email.create! valid_attributes
      get emails_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      email = Email.create! valid_attributes
      get email_url(email)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_email_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      email = Email.create! valid_attributes
      get edit_email_url(email)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Email" do
        expect {
          post emails_url, params: { email: valid_attributes }
        }.to change(Email, :count).by(1)
      end

      it "redirects to the created email" do
        post emails_url, params: { email: valid_attributes }
        expect(response).to redirect_to(email_url(Email.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Email" do
        expect {
          post emails_url, params: { email: invalid_attributes }
        }.to change(Email, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post emails_url, params: { email: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested email" do
        email = Email.create! valid_attributes
        patch email_url(email), params: { email: new_attributes }
        email.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the email" do
        email = Email.create! valid_attributes
        patch email_url(email), params: { email: new_attributes }
        email.reload
        expect(response).to redirect_to(email_url(email))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        email = Email.create! valid_attributes
        patch email_url(email), params: { email: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested email" do
      email = Email.create! valid_attributes
      expect {
        delete email_url(email)
      }.to change(Email, :count).by(-1)
    end

    it "redirects to the emails list" do
      email = Email.create! valid_attributes
      delete email_url(email)
      expect(response).to redirect_to(emails_url)
    end
  end
end
