require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/numbers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Number. As you add validations to Number, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Number.create! valid_attributes
      get numbers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      number = Number.create! valid_attributes
      get number_url(number)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_number_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      number = Number.create! valid_attributes
      get edit_number_url(number)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Number" do
        expect {
          post numbers_url, params: { number: valid_attributes }
        }.to change(Number, :count).by(1)
      end

      it "redirects to the created number" do
        post numbers_url, params: { number: valid_attributes }
        expect(response).to redirect_to(number_url(Number.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Number" do
        expect {
          post numbers_url, params: { number: invalid_attributes }
        }.to change(Number, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post numbers_url, params: { number: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested number" do
        number = Number.create! valid_attributes
        patch number_url(number), params: { number: new_attributes }
        number.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the number" do
        number = Number.create! valid_attributes
        patch number_url(number), params: { number: new_attributes }
        number.reload
        expect(response).to redirect_to(number_url(number))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        number = Number.create! valid_attributes
        patch number_url(number), params: { number: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested number" do
      number = Number.create! valid_attributes
      expect {
        delete number_url(number)
      }.to change(Number, :count).by(-1)
    end

    it "redirects to the numbers list" do
      number = Number.create! valid_attributes
      delete number_url(number)
      expect(response).to redirect_to(numbers_url)
    end
  end
end
